name: evemanager
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_rating_bar: ^4.0.0
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  firebase_core: ^2.24.2
  firebase_storage: ^11.6.0
  firebase_auth: ^4.16.0
  fluttertoast: ^8.2.4
  firebase_database: ^10.4.0
  get_it: ^7.2.0
  http: ^1.2.0
  path_provider: ^2.1.2
  image_picker: ^1.0.7
  cloud_firestore: ^4.15.10

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
