// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDs9MhqLCHGM0P2PFehW3CjsmovFfdRClI',
    appId: '1:186952557679:web:db929614e9f6647d4c199a',
    messagingSenderId: '186952557679',
    projectId: 'evemanage-4418c',
    authDomain: 'evemanage-4418c.firebaseapp.com',
    storageBucket: 'evemanage-4418c.appspot.com',
    measurementId: 'G-Y5167TCMDP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSdfmTc9S5uG41YLw_h6DyRagWcytezyY',
    appId: '1:186952557679:android:52e8bc291a320b8d4c199a',
    messagingSenderId: '186952557679',
    projectId: 'evemanage-4418c',
    storageBucket: 'evemanage-4418c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_c59G7VFkdZWaGJuHcY95YCiGwjpdLmo',
    appId: '1:186952557679:ios:0cdbd1bae2285afc4c199a',
    messagingSenderId: '186952557679',
    projectId: 'evemanage-4418c',
    storageBucket: 'evemanage-4418c.appspot.com',
    iosBundleId: 'revodev.evemanager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_c59G7VFkdZWaGJuHcY95YCiGwjpdLmo',
    appId: '1:186952557679:ios:758a82f0ebb313104c199a',
    messagingSenderId: '186952557679',
    projectId: 'evemanage-4418c',
    storageBucket: 'evemanage-4418c.appspot.com',
    iosBundleId: 'revodev.evemanager.RunnerTests',
  );
}
